# Generated by Django 4.0 on 2022-01-06 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('body', models.TextField(blank=True, verbose_name='Body')),
                ('done', models.BooleanField(default=False, verbose_name='Done?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('plans', models.ManyToManyField(related_name='plans', through='plans.PlannedTodo', to='plans.Plan')),
            ],
        ),
    ]
