# Generated by Django 4.0 on 2022-01-07 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sets', '0001_initial'),
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='sets',
            field=models.ManyToManyField(related_name='sets', through='sets.SetLink', to='sets.Set'),
        ),
    ]
