# Generated by Django 4.0 on 2022-01-10 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='label',
            field=models.CharField(blank=True, max_length=500, verbose_name='Label'),
        ),
    ]
